"""empty message

Revision ID: ec8c23ae08a4
Revises: d4392342465f
Create Date: 2021-08-19 18:10:01.255505

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8c23ae08a4'
down_revision = 'd4392342465f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION pg_trgm')
    op.create_index('note_pg_trgm_index', 'alias', ['note'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('note_pg_trgm_index', table_name='alias')
    op.execute('DROP EXTENSION pg_trgm')
    # ### end Alembic commands ###
